name: zflutter_gallery
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  zflutter:
    git:
      url: https://github.com/IbrahimTabba/zflutter.git
      ref: null-safety

  provider: ^6.0.1
  synchronized: ^3.0.0
  cupertino_icons: ^1.0.2
  stop_watch_timer: ^1.3.1
  lottie: ^1.2.1
  flutter_svg: ^1.0.0
  shared_preferences: ^2.0.11
  get_it: ^7.2.0
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323/VT323-Regular.ttf
          weight: 400

  assets:
    - assets/animations/
    - assets/svg/
    - assets/images/